In [91]:
import numpy as np
import pandas as pd
import plotly.express as px
import pickle
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [92]:
df = pd.read_csv('../data_samples/data_prep.csv')
df

Region   Age   Income Online Shoper
0   india  49.0  86400.0            No
1     USA  35.0  57600.0           Yes
2  Brazil  43.0  73200.0            No
3     USA  45.0      NaN           Yes
4   India  40.0  60600.0           Yes
5     USA  55.0  99600.0            No
6  Brazil   NaN  62400.0            No
7   India  42.0  80400.0           Yes

In [93]:
X = df.iloc[: , :-1].values
y= df.iloc[ : , -1].values
print(X )
print(f'\n {y}')

[['india' 49.0 86400.0]
 ['USA' 35.0 57600.0]
 ['Brazil' 43.0 73200.0]
 ['USA' 45.0 nan]
 ['India' 40.0 60600.0]
 ['USA' 55.0 99600.0]
 ['Brazil' nan 62400.0]
 ['India' 42.0 80400.0]]

 ['No' 'Yes' 'No' 'Yes' 'Yes' 'No' 'No' 'Yes']


In [94]:

si = SimpleImputer(missing_values=np.nan , strategy='mean')
si.fit(X[: , 1:])
X[: ,1:]=si.transform(X[:, 1:])


In [95]:
new_data_for_test = np.array([['Iran' , 23 ,np.nan]])
si.transform(new_data_for_test[: , 1:])

array([[2.30000000e+01, 7.43142857e+04]])

In [96]:
# with open('si.h5' , 'wb') as f :
#     pickle.dump(si, f)

In [97]:
# with open ('si.h5' ,'rb') as f :
#     si2 = pickle.load(f)

In [98]:

le = LabelEncoder()
X[: , 0] = le.fit_transform(X[: , 0])
X


array([[3, 49.0, 86400.0],
       [2, 35.0, 57600.0],
       [0, 43.0, 73200.0],
       [2, 45.0, 74314.28571428571],
       [1, 40.0, 60600.0],
       [2, 55.0, 99600.0],
       [0, 44.142857142857146, 62400.0],
       [1, 42.0, 80400.0]], dtype=object)

In [99]:
ct = ColumnTransformer([('Country' , OneHotEncoder(),[0])] , remainder='passthrough')
X=ct.fit_transform(X)
X

array([[0.0, 0.0, 0.0, 1.0, 49.0, 86400.0],
       [0.0, 0.0, 1.0, 0.0, 35.0, 57600.0],
       [1.0, 0.0, 0.0, 0.0, 43.0, 73200.0],
       [0.0, 0.0, 1.0, 0.0, 45.0, 74314.28571428571],
       [0.0, 1.0, 0.0, 0.0, 40.0, 60600.0],
       [0.0, 0.0, 1.0, 0.0, 55.0, 99600.0],
       [1.0, 0.0, 0.0, 0.0, 44.142857142857146, 62400.0],
       [0.0, 1.0, 0.0, 0.0, 42.0, 80400.0]], dtype=object)

In [100]:
ss=StandardScaler()
X=ss.fit_transform(X)
X

array([[-0.57735027, -0.57735027, -0.77459667,  2.64575131,  0.87086496,
         0.90297925],
       [-0.57735027, -0.57735027,  1.29099445, -0.37796447, -1.63927521,
        -1.24880109],
       [ 1.73205081, -0.57735027, -0.77459667, -0.37796447, -0.2049094 ,
        -0.08325341],
       [-0.57735027, -0.57735027,  1.29099445, -0.37796447,  0.15368205,
         0.        ],
       [-0.57735027,  1.73205081, -0.77459667, -0.37796447, -0.74279658,
        -1.0246573 ],
       [-0.57735027, -0.57735027,  1.29099445, -0.37796447,  1.94663932,
         1.8892119 ],
       [ 1.73205081, -0.57735027, -0.77459667, -0.37796447,  0.        ,
        -0.89017103],
       [-0.57735027,  1.73205081, -0.77459667, -0.37796447, -0.38420513,
         0.45469168]])

In [101]:
# with open('le.h5','wb') as f:
#     pickle.dump(le, f)
# with open('ct.h5','wb') as f:
#     pickle.dump(le, f)
# with open('ss.h5','wb') as f:
#     pickle.dump(le, f)