In [75]:
import numpy as np
import pandas as pd
import plotly.express as px
import pickle
from sklearn.impute import KNNImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import Binarizer

import plotly.express as px

In [76]:
df = pd.read_csv('../data_samples/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [77]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [78]:
fig = px.histogram(df , x='Insulin',color='Outcome')
fig.show()

In [79]:
skines = df[df['SkinThickness'] ==0]
skines

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
2              8      183             64              0        0  23.3   
5              5      116             74              0        0  25.6   
7             10      115              0              0        0  35.3   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
..           ...      ...            ...            ...      ...   ...   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
762            9       89             62              0        0  22.5   
766            1      126             60              0        0  30.1   

     DiabetesPedigreeFunction  Age  Outcome  
2                       0.672   32        1  
5                       0.201   30        0  
7                       0.134   29        0  
9                       0.232   54        1  
10                      0.191   30        0  
..                        ...  ...      ...  
757                     0.258   52        1  
758                     0.197   26        0  
759                     0.278   66        1  
762                     0.142   33        0  
766                     0.349   47        1  

[227 rows x 9 columns]

In [80]:
skin_mean =df[df['SkinThickness'] != 0]['SkinThickness'].mean()
skin_mean

29.153419593345657

In [81]:
df.replace({'SkinThickness' : 0},skin_mean,inplace=True)
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72       35.00000        0  33.6   
1              1       85             66       29.00000        0  26.6   
2              8      183             64       29.15342        0  23.3   
3              1       89             66       23.00000       94  28.1   
4              0      137             40       35.00000      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76       48.00000      180  32.9   
764            2      122             70       27.00000        0  36.8   
765            5      121             72       23.00000      112  26.2   
766            1      126             60       29.15342        0  30.1   
767            1       93             70       31.00000        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [82]:
fig = px.histogram(df , x='SkinThickness')
fig.show()

In [83]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      29.153420   79.799479   
std       3.369578   31.972618      19.355807       8.790942  115.244002   
min       0.000000    0.000000       0.000000       7.000000    0.000000   
25%       1.000000   99.000000      62.000000      25.000000    0.000000   
50%       3.000000  117.000000      72.000000      29.153420   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [84]:
df = pd.read_csv('../data_samples/diabetes.csv')
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [85]:
df.replace({'SkinThickness':0 , 'Insulin':0} , np.nan , inplace=True)
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72           35.0      NaN  33.6   
1              1       85             66           29.0      NaN  26.6   
2              8      183             64            NaN      NaN  23.3   
3              1       89             66           23.0     94.0  28.1   
4              0      137             40           35.0    168.0  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76           48.0    180.0  32.9   
764            2      122             70           27.0      NaN  36.8   
765            5      121             72           23.0    112.0  26.2   
766            1      126             60            NaN      NaN  30.1   
767            1       93             70           31.0      NaN  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [86]:

imput = KNNImputer(n_neighbors=3)
df = imput.fit_transform(df.iloc[: , :-1])
df

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [87]:
scaler = MinMaxScaler(feature_range=(0,1))
df = scaler.fit_transform(df)
df

array([[0.35294118, 0.74371859, 0.59016393, ..., 0.50074516, 0.23441503,
        0.48333333],
       [0.05882353, 0.42713568, 0.54098361, ..., 0.39642325, 0.11656704,
        0.16666667],
       [0.47058824, 0.91959799, 0.52459016, ..., 0.34724292, 0.25362938,
        0.18333333],
       ...,
       [0.29411765, 0.6080402 , 0.59016393, ..., 0.390462  , 0.07130658,
        0.15      ],
       [0.05882353, 0.63316583, 0.49180328, ..., 0.4485842 , 0.11571307,
        0.43333333],
       [0.05882353, 0.46733668, 0.57377049, ..., 0.45305514, 0.10119556,
        0.03333333]])

In [88]:
sc=StandardScaler()
df = sc.fit_transform(df)
df

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [89]:
norm = Normalizer()
df = norm.fit_transform(df)
df

array([[ 0.32362275,  0.42899923,  0.07567366, ...,  0.10316971,
         0.23691744,  0.72112905],
       [-0.46076665, -0.61265562, -0.08755525, ..., -0.37325646,
        -0.1990896 , -0.10398486],
       [ 0.4614327 ,  0.7268921 , -0.09870579, ..., -0.41258313,
         0.22602574, -0.03948518],
       ...,
       [ 0.25636337,  0.00246726,  0.11185001, ..., -0.54952258,
        -0.51215251, -0.20611846],
       [-0.48273672,  0.09129627, -0.26895936, ..., -0.1372442 ,
        -0.21203368,  0.66891394],
       [-0.47216678, -0.48788964,  0.02584431, ..., -0.11296035,
        -0.26477633, -0.48697017]])

In [90]:
np.sum(df[0] ** 2)

1.0

In [91]:
bina = Binarizer(threshold=0.0)
data_b = bina.fit_transform(df)
data_b


array([[1., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [92]:
np.concatenate((df,data_b), axis=1)

array([[ 0.32362275,  0.42899923,  0.07567366, ...,  1.        ,
         1.        ,  1.        ],
       [-0.46076665, -0.61265562, -0.08755525, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.4614327 ,  0.7268921 , -0.09870579, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 0.25636337,  0.00246726,  0.11185001, ...,  0.        ,
         0.        ,  0.        ],
       [-0.48273672,  0.09129627, -0.26895936, ...,  0.        ,
         0.        ,  1.        ],
       [-0.47216678, -0.48788964,  0.02584431, ...,  0.        ,
         0.        ,  0.        ]])